WEBHOOK_PASSPHRASE = "Suneesh_Passphrase"
API_KEY = b'etdTQ3qe3QGf1x2aG2FMOWYIn9yfEMDDB0QSAoQ7y6TRcGW9fSqjsZa6ta9mYXbx'
API_SECRET = 'gmPbtIuQ1nu4ilGTDc5e09tXjtxBakO0ECYGF8s4tyJ33874froVe6pBmqXUm5OO'
DEBUG_MODE = True
ENABLE_TV_SIGNAL_SIGNATURE_CHECK = False

RESPONSE = "response"
MESSAGE = "message"
STATUS = "status"
SUCCESS = "Success"
FAIL = "Fail"
